AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-trial-app

  Sample SAM Template for sam-trial-app

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The name of the API Gateway stage to deploy.

Globals:
  Function:
    Timeout: 3

Resources:
  TodoDatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: resources/dynamodb.yaml
      Parameters:
        TodoTableName:
          Fn::Sub: "${AWS::StackName}-${StageName}-Todos"

Outputs:
  TodoTableName:
    Description: "Name of the DynamoDB table for Todos"
    Value:
      Fn::GetAtt:
        - TodoDatabaseStack
        - Outputs.TodoTableName
