AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Todo API - Root Stack

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The name of the API Gateway stage to deploy.
  TodoTableName:
    Type: String
    Default: todos
    Description: The name of the DynamoDB table for Todos.
  ImageBucketName:
    Type: String
    Default: todo-api-image-storage
    Description: The name of the S3 bucket for image.

Resources:
  TodoApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/api.yaml
      Parameters:
        StageName:
          Ref: StageName
        TodoTableName:
          Ref: TodoTableName
        ImageBucketName:
          Ref: ImageBucketName

  TodoTableStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/dynamodb.yaml
      Parameters:
        TodoTableName:
          Ref: TodoTableName

  ImageBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/s3.yaml
      Parameters:
        ImageBucketName:
          Ref: ImageBucketName

Outputs:
  TodoApiUrl:
    Description: "API Gateway endpoint URL"
    Value:
      Fn::GetAtt:
        - TodoApiStack
        - Outputs.TodoApiUrl

  TodoTableName:
    Description: "DynamoDB Table Name for Todos"
    Value:
      Fn::GetAtt:
        - TodoTableStack
        - Outputs.TodoTableName

  ImageBucketName:
    Description: "S3 Bucket Name for Images"
    Value:
      Fn::GetAtt:
        - ImageBucketStack
        - Outputs.ImageBucketName
