AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Todo API - Root Stack

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The name of the API Gateway stage to deploy.

Resources:
  TodosDomainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/todos/template.yaml
      Parameters:
        StageName:
          Ref: StageName
      Tags:
        - Key: Project
          Value: TodoAPI
        - Key: Environment
          Value: 
            Ref: StageName

Outputs:
  TodoTableName:
    Description: "DynamoDB Table Name for Todos"
    Value:
      Fn::GetAtt:
        - TodosDomainStack
        - Outputs.TodoTableName
  TodoBucketName:
    Description: "S3 Bucket Name for Images"
    Value:
      Fn::GetAtt:
        - TodosDomainStack
        - Outputs.TodoBucketName
