AWSTemplateFormatVersion: '2010-09-09'
Description: >
  TodoAPI - S3 Storage Stack for images.

Parameters:
  TodoBucketName:
    Type: String
    Default: sam-todo-api-storage
    Description: The name of the S3 bucket for images.

Resources:
  TodoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: TodoBucketName
      # バケット自体はプライベートにする
      # 署名付きURLなどでアクセスを制御する
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              # 開発中は全てのオリジンを許可してもいいが、
              # 本番ではフロントエンドのドメインに限定するべきです
              - "*"
      Tags:
        - Key: Project
          Value: TodoAPI
        - Key: Environment
          Value:
            Fn::Sub: "${AWS::StackName}"
        - Key: Domain
          Value: Todos

Outputs:
  TodoBucketName:
    Description: "Name of the S3 bucket for images"
    Value:
      Ref: TodoBucket
