AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Todo API - Todos Domain Stack.

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The name of the API Gateway stage to deploy.

Resources:
  TodoDatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: dynamodb.yaml
      Parameters:
        TodoTableName:
          Fn::Sub: "${AWS::StackName}-${StageName}-Todos"
      Tags:
        - Key: Project
          Value: TodoAPI
        - Key: Environment
          Value: 
            Fn::Sub: "${AWS::StackName}"

  TodoStorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: s3.yaml
      Tags:
        - Key: Project
          Value: TodoAPI
        - Key: Environment
          Value: 
            Fn::Sub: "${AWS::StackName}"
  
  TodoApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: api.yaml
      Parameters:
        StageName:
          Ref: StageName
        TodoTableName:
          Fn::GetAtt:
            - TodoDatabaseStack
            - Outputs.TodoTableName
        TodoBucketName:
          Fn::GetAtt:
            - TodoStorageStack
            - Outputs.TodoBucketName
      Tags:
        - Key: Project
          Value: TodoAPI
        - Key: Environment
          Value: 
            Fn::Sub: "${AWS::StackName}"
        - Key: Domain
          Value: Todos

Outputs:
  TodoTableName:
    Description: "DynamoDB Table Name for Todos"
    Value:
      Fn::GetAtt:
        - TodoDatabaseStack
        - Outputs.TodoTableName
  TodoBucketName:
    Description: "S3 Bucket Name for Images"
    Value:
      Fn::GetAtt:
        - TodoStorageStack
        - Outputs.TodoBucketName
  TodoApiUrl:
    Description: "API Gateway endpoint URL for Todo API"
    Value:
      Fn::GetAtt:
        - TodoApiStack
        - Outputs.TodoApiUrl
