AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Todo API - Todos Domain Stack.

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The name of the API Gateway stage to deploy.

Resources:
  TodosDatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: dynamodb.yaml
      Parameters:
        TodoTableName:
          Fn::Sub: "${AWS::StackName}-${StageName}-Todos"
      Tags:
        - Key: Project
          Value: TodoAPI
        - Key: Environment
          Value: 
            Fn::Sub: "${AWS::StackName}"

Outputs:
  TodoTableName:
    Description: "DynamoDB Table Name for Todos"
    Value:
      Fn::GetAtt:
        - TodosDatabaseStack
        - Outputs.TodoTableName
