AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Todo API - DynamoDB Stack

Parameters:
  TodoTableName:
    Type: String
    Description: The name of the DynamoDB table for Todos.

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        Ref: TodoTableName
      AttributeDefinitions:
        - AttributeName: todo_id
          AttributeType: S
      KeySchema:
        - AttributeName: todo_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: TodoAPI
        - Key: Environment
          Value: 
            Fn::Sub: "${AWS::StackName}"
        - Key: Domain
          Value: Todos

Outputs:
  TodoTableName:
    Description: "Name of the DynamoDB table for Todos"
    Value: 
      Ref: TodoTable
