AWSTemplateFormatVersion: '2010-09-09'
Description: >
  TodoAPI - S3 Storage Stack for image.

Parameters:
  ImageBucketName:
    Type: String
    Description: The name of the S3 bucket for image.

Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: ImageBucketName
      # バケット自体はプライベートにする
      # 署名付きURLなどでアクセスを制御する
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              # 開発中は全てのオリジンを許可してもいいが、
              # 本番ではフロントエンドのドメインに限定するべき
              - "*"
      Tags:
        - Key: Project
          Value: TodoAPI
        - Key: Environment
          Value:
            Fn::Sub: "${AWS::StackName}"
        - Key: Domain
          Value: Image

Outputs:
  ImageBucketName:
    Description: "Name of the S3 bucket for image"
    Value:
      Ref: ImageBucket
