name: Deploy-AWS-SAM-Application

on:
  push:
    branches:
      - 'main'

env:
  TEMPLATE_FILE: template.yaml
  SAM_CLI_TELEMETRY: 0

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::739275444833:role/aws-sam-todo-api-github-actions-role
          aws-region: ap-northeast-1
          role-session-name: SamDeploy
      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
